package com.te.addressapp.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.*;

@AllArgsConstructor
@NoArgsConstructor
@Setter
@Getter
@Builder
@DynamoDBTable(tableName = "address_service_tb")
public class Address {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String addressid;

    @DynamoDBAttribute
    private String city;

    @DynamoDBAttribute
    private String state;

}
